version: '3.8'

services:
    api:
        build:
            args:
                user: cyril
                uid: 1000
            context: .
            dockerfile: api/Dockerfile
        image: travellist
        container_name: api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./api/:/var/www
        networks:
            - travellist
    db:
        image: mariadb:10.4-focal
        container_name: db
        restart: unless-stopped
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 3326:3306
        networks:
            - travellist
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8100:80
        volumes:
            - ./api:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
